name: GitHub CI

on:
-   push
-   pull_request
-   workflow_dispatch

jobs:
    windowsBuild:
        name: Windows Build
        runs-on: windows-latest
        env:
            BUILD_PROJECT: llvm
            BUILD_MASTER: false
            LLVM_VERSION: 16.0.5

        strategy:
            fail-fast: false
            matrix:
                CRT:
                -   msvcrt
                -   libcmt

                TARGET_CPU:
                -   x86
                -   amd64

                CONFIGURATION:
                -   Debug
                -   Release

        steps:
        -   name: Checkout repo
            uses: actions/checkout@v2

        -   name: Get number of CPU cores
            uses: SimenB/github-actions-cpu-cores@v1
            id: cpu-cores

        -   name: Configure Pagefile
            uses: al-cheb/configure-pagefile-action@v1.2
            with:
                minimum-size: 16GB
                disk-root: "C:"

        -   name: Setup MSVC
            uses: ilammy/msvc-dev-cmd@v1
            with:
                vsversion: 2022

        -   name: Install
            shell: cmd
            run: |
                call %GITHUB_WORKSPACE%\set-env.bat ${{ steps.cpu-cores.outputs.count }} msvc17 ${{matrix.CRT}} ${{matrix.TARGET_CPU}} ${{matrix.CONFIGURATION}}
                call %GITHUB_WORKSPACE%\install.bat

        -   name: Build and test
            id: BUILD
            shell: cmd
            run: |
                call %GITHUB_WORKSPACE%\set-env.bat ${{ steps.cpu-cores.outputs.count }} msvc17 ${{matrix.CRT}} ${{matrix.TARGET_CPU}} ${{matrix.CONFIGURATION}}
                call %GITHUB_WORKSPACE%\build.bat
                echo ::set-output name=DEPLOY_FILE::%DEPLOY_FILE%

        -   name: Release
            uses: softprops/action-gh-release@v1
            if: startsWith(github.ref, 'refs/tags/')
            with:
                files: ${{steps.BUILD.outputs.DEPLOY_FILE}}
